version: '3.9'

services:
  mysql_inventory:
    image: mysql:8.0-debian
    container_name: mysql_inventory
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_inventory
    volumes:
      - data-mysql-inventory:/var/lib/mysql
    restart: always
    networks:
      - microservices_network


volumes:
  data-mysql-inventory:

networks:
  microservices_network:
    driver: bridge